databases:
  - name: skillmatch_db
    databaseName: skillmatch
    user: skillmatch_user

services:
  - type: web
    name: skillmatch-hub
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn skillmatch_hub.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skillmatch_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.13.0
